// Copyright (C) 2026 RHVoice contributors
// SPDX-License-Identifier: LGPL-2.1-or-later

import AppKit
import Foundation

/// Creators, license and links for a voice.
struct VoiceAttribution: Sendable, Equatable {
    var creators: [String] = []
    var copyright: String?
    var licenseName: String?
    var licenseURL: URL?
    var homepage: URL?
    /// Plain-text rendering of the pack's attrib.html, when installed.
    var attributionText: String?

    var isEmpty: Bool {
        creators.isEmpty && copyright == nil && licenseName == nil && attributionText == nil
    }
}

/// Bundled table generated by scripts/generate-voice-metadata.py from the voice repositories
/// (Resources/voice-metadata.json), keyed by package id.
struct BundledVoiceMetadata: Codable, Sendable {
    struct License: Codable, Sendable {
        var spdx: String?
        var name: String
        var url: String?
    }

    struct Entry: Codable, Sendable {
        var license: License?
        var creators: [String]?
        var copyright: String?
        var homepage: String?
        var source: String?
    }

    var voices: [String: Entry]

    static func load() -> BundledVoiceMetadata {
        guard let url = Bundle.main.url(forResource: "voice-metadata", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let decoded = try? JSONDecoder().decode(BundledVoiceMetadata.self, from: data) else {
            return BundledVoiceMetadata(voices: [:])
        }
        return decoded
    }
}

enum VoiceMetadataStore {
    nonisolated(unsafe) private static let bundled = BundledVoiceMetadata.load()

    /// Attribution for a voice: the bundled table first, then the installed pack's attrib.html.
    @MainActor
    static func attribution(voiceId: String, installedDirectory: URL?) -> VoiceAttribution {
        var result = VoiceAttribution()
        if let entry = bundled.voices[voiceId] {
            result.creators = entry.creators ?? []
            result.copyright = entry.copyright
            result.licenseName = entry.license?.name
            result.licenseURL = entry.license?.url.flatMap { URL(string: $0) }
            result.homepage = entry.homepage.flatMap { URL(string: $0) }
        }
        // The pack's own attrib.html is the source of truth once installed, but it repeats the
        // bundled table for voices that have an entry there; show it only when the table lacks one.
        if let installedDirectory, bundled.voices[voiceId]?.license == nil {
            let html = installedDirectory.appendingPathComponent("attrib.html")
            if let data = try? Data(contentsOf: html),
               let attributed = try? NSAttributedString(data: data, options: [.documentType: NSAttributedString.DocumentType.html, .characterEncoding: String.Encoding.utf8.rawValue], documentAttributes: nil) {
                let text = attributed.string.trimmingCharacters(in: .whitespacesAndNewlines)
                    .replacingOccurrences(of: "\n\n", with: "\n")
                if !text.isEmpty {
                    result.attributionText = text
                }
                if result.licenseURL == nil {
                    attributed.enumerateAttribute(.link, in: NSRange(location: 0, length: attributed.length)) { value, _, _ in
                        if result.licenseURL == nil, let url = value as? URL, url.host?.contains("creativecommons") == true || url.path.contains("licenses") {
                            result.licenseURL = url
                        }
                    }
                }
            }
        }
        return result
    }
}
