#!/bin/bash
# Build a macOS target of RHVoice.
#
#   scripts/build.sh [scheme] [extra xcodebuild args...]
#
# Defaults to the RHVoice app scheme and the Release configuration; set CONFIGURATION=Debug
# to change it. Regenerates RHVoice.xcodeproj from project.yml (XcodeGen) when the spec is
# newer than the project. Output goes to src/macos/build/DerivedData.
set -euo pipefail
cd "$(dirname "$0")/.."

for f in ../core/config.h ../include/core/config.h; do
  if [ -e "$f" ]; then
    echo "error: $f exists. It was generated by a SCons or CMake build and would shadow" >&2
    echo "       RHVoiceCore/include/config.h. Remove it before building the macOS targets." >&2
    exit 1
  fi
done

if [ ! -f RHVoice.xcodeproj/project.pbxproj ] || [ project.yml -nt RHVoice.xcodeproj/project.pbxproj ]; then
  if ! command -v xcodegen >/dev/null 2>&1; then
    echo "error: xcodegen not found (brew install xcodegen)" >&2
    exit 1
  fi
  xcodegen generate
fi

scheme="${1:-RHVoice}"
shift $(( $# > 0 ? 1 : 0 ))
configuration="${CONFIGURATION:-Release}"

xcodebuild -project RHVoice.xcodeproj \
  -scheme "$scheme" \
  -configuration "$configuration" \
  -derivedDataPath build/DerivedData \
  "$@" build
